### ISSUE TITLE
Why MQTT?

### ISSUE THREAD

**Issue by TintypeMolly** [openirc/openirc#47]
프로젝트에 관심이 있어서 기여할 곳이 있을까 찾아보고 있었습니다.

프로젝트 구조나 왜 openirc를 만드려고 하는지에 대해서나,

어떤 기술을 사용하기로 한 선택들의 이유가 잘 써있어서 이해하는 데에 도움이 됐습니다.

다만 websocket only라던지 WAMP 아니라 MQTT를 선택한 이유에 대해서는 언급이 없고,

그 부분에 대해서 이유를 알고 싶습니다.

해당 부분에 대해서 문서를 업데이트 해주실 수 있을런지요?

**Comment by simnalamburt** [comment]
I'll update the document if I have some spare time. I'm answering your question in here for right now.

### Why use MQTT over websocket?
There's no other way to use MQTT in web browser excepting using Adobe Flash plug-in. Flash is dead technology and there's no good reason to avoid using websocket. Websocket is widely adopted technology, so we decided to just use MQTT over websocket.

### Why MQTT
MQTT is an extremely lightweight publish/subscribe messaging protocol. And as far as I know MQTT suits all the needs to implement simple chat app. MQTT has proved its usefulness and has been battle tested over a decade with Facebook native client. It has been supported by RabbitMQ and HiveMQ, and so it will continue to be supported and standardized as M2M communication protocol.

###### Reference
- [Building Facebook Messenger, by Facebook Message Team](https://www.facebook.com/notes/facebook-engineering/building-facebook-messenger/10150259350998920/)

### Why not STOMP
STOMP's only advantage over MQTT is ease of protocol implementation which is not the case for this project. We're just simply use already developed protocol libraries so STOMP was not an option at all

### Why not AMQP
AMQP is good protocol but it was too complex compared to our simple needs; a chatting protocol.

### Why not WAMP
It's specialized for web.
